### ISSUE TITLE
Problem after the single point energy calculation by orca

### ISSUE THREAD

**Issue by palapurba** [MatthijsHak/MetalDock#15]
Try to dock a Iron-ligand coordination complex with a nucleic acid structure. Here Iron atom do not having vacant coordination site. I skipped the geometry optimization step as  I want to dock the exact conformation of Metal-Ligand complex found from the crystal structure. So after single point converged it is showing an error with a nitrogen atom from the ligand which make coordination bond iron metal centre. This nitrogen atom is in sp2 hybridization but it not showing from the calculation. Requesting you kindly help me to find a probable solutions to get out from this problem. Thank you
![Screenshot from 2024-01-20 15-06-33](https://github.com/MatthijsHak/MetalDock/assets/157197579/e1696a96-f13f-4707-a97e-7d92408ba2a8)

**Comment by MatthijsHak** [comment]
Could you share with me your input and output files?

**Comment by palapurba** [comment]
Dear Matthijs,
Thank you for your reply. As I am working with a new set of problems which is yet to publish, therefore I am little bit concerned about the data to make it public. If you kindly provide your personal contact details then I will share the data with you.

**Comment by MatthijsHak** [comment]
I completely understand. You can send the files to m.l.a.hakkennes@lic.leidenuniv.nl. I will then have a look at it.

**Comment by palapurba** [comment]
I have sent the input and output file to your mail id. Please have a look at it.
