### ISSUE TITLE
Requesting for PDB and .xyz files to try running MetalDock on my own

### ISSUE THREAD

**Issue by yipy0005** [MatthijsHak/MetalDock#16]
Hi, I'm new to MetalDock and it looks very applicable to the work I'm doing right now. Could I request a metal parameter file, a pdb file and an organometallic_compound.xyz file so that I can try running MetalDock on my machine?

Much appreciated.
Yew Mun

**Comment by MatthijsHak** [comment]
Dear Yew,

The parameter file is present in the github repositiory, and if you do not specify a specific parameter file, MetalDock will use this parameter file. 

[example_MetalDock.zip](https://github.com/MatthijsHak/MetalDock/files/14084626/example_MetalDock.zip)

I have added the example similar to case study 2 in the paper:

https://doi.org/10.1021/acs.jcim.3c01582

Hope this helps.

Regards,

Matthijs

**Comment by yipy0005** [comment]
Hi Matthijs,

That really helps a lot! I have managed to run it, so all's good with running Metaldock against the example. :D
This is really a great piece of work, and I appreciate that you responded to my query. Thank you so much. :)

Best regards,
Yew Mun

**Comment by MatthijsHak** [comment]
No problem Yew, I am glad you like it! :)
