### ISSUE TITLE
MetalDock errors out during docking

### ISSUE THREAD

**Issue by StefanIvanovIBBR** [MatthijsHak/MetalDock#24]
(base) stefan@stefan-Latitude-5521:~$ MetalDock/metaldock -i orca_input.ini 
SINGLE POINT CONVERGED
SPACING BETWEEN GRID POINTS IS STANDARD SET TO 0.375 Å
BOX SIZE MUST BE INTEGER GRID POINTS WHICH WAS NOT FOUND
BOX SIZE SIDE ROUNDED UP AND SET TO 20.301 Å

Traceback (most recent call last):
  File "/home/stefan/MetalDock/metaldock", line 6, in <module>
    main()
  File "/home/stefan/MetalDock/src/metal_dock/main.py", line 18, in main
    docking(par)
  File "/home/stefan/MetalDock/src/metal_dock/docking.py", line 139, in docking
    d.create_ligand_pdbqt_file(par, par.name_ligand)
  File "/home/stefan/MetalDock/src/metal_dock/prepare_dock.py", line 246, in create_ligand_pdbqt_file
    multiple_model_file(par, name_ligand, f'{name_ligand}_c.xyz', f'{name_ligand}.pdbqt')
  File "/home/stefan/MetalDock/src/metal_dock/prepare_dock.py", line 313, in multiple_model_file
    for line in mol[f'mol_{metal_mdl}']:
                           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'metal_mdl' where it is not associated with a value
[orca_input.zip](https://github.com/MatthijsHak/MetalDock/files/15044246/orca_input.zip)

**Comment by MatthijsHak** [comment]
Hi,

In your xyz file you use Iron (Fe) as metal, but as input you set the metal_symbol to Pt. I think this is the problem. Let me know if it resolves it.

**Comment by StefanIvanovIBBR** [comment]
Ah, silly me, I forgot to change the metal atom from Pt to Fe. Thanks for pointing that out. Sadly, parameters for Fe are currently not available. What would you suggest I do in this situation? Could you please provide tentative parameters @MatthijsHak ? At this point rough parameters are better than no parameters.

**Comment by MatthijsHak** [comment]
Hi,

Parameters for Iron are already present in AutoDock, and therefore in MetalDock as well. I have ran your calculation and everything looks fine, except for the centre of the box. This is not within or around the pocket.
