### ISSUE TITLE
CM5 charge calculation

### ISSUE THREAD

**Issue by Saem5075** [MatthijsHak/MetalDock#25]
Hi, Regarding partial charge (CM5) calculation, I am getting normalized CM5 in my .mol2 and .pdbqt file of my metal complex of interest. I am guessing normalized because while sum all of my partial charges (CM5), it's total approximately zero, whereas my formal charge of complex is -8. Then I looked up the orca2CM5.py script, where in line 91: df['QCM5']     = np.array(cm5_charges) - np.mean(cm5_charges), which is designed to center the charges around zero, I guess.

As far as my understanding goes, qcm5= qHir+factor*(.....), which means CM5 charge would be the Hirshfield charge + correction factor. Also the summation of CM5 would be equal to summation of Hirshfield charges. 

I am bit confused with line 91, do I need to normalize the CM5 charge or I can just use CM5 charge that I get from the equation? Thank you so much.

**Comment by MatthijsHak** [comment]
Hi,

Thank you for spotting this problem, as I did not encounter this myself. You are correct that the CM5 charges do not need to be normalized. I have adjusted this in the new repo and believe that the CM5 charges of charged species should now be calculated properly. I verified this by comparing the charges generated by ORCA with ADF and they seem to agree with each other. Hopefully, if you run the new version it will give you satisfactory results. Let me know if you encounter any other problems.
