### ISSUE TITLE
MetalDock Setup -- Gaussian16 Linux

### ISSUE THREAD

**Issue by rjrich** [MatthijsHak/MetalDock#27]
In the MetalDock setup instructions for Gaussian16, it says to export the following environment variable:

export g16root=/full/path/to/gaussian/g16

However, according to the Gaussian16 installation instructions, this variable should be set as follows (for my system):

# Gaussian16
export g16root="/home/rjrich/zware"
export GAUSS_SCRDIR="/home/data1/gau_scratch"
. $g16root/g16/bsd/g16.profile

I have it already set up in my system as shown above in my ".profile" file, and if I enter "g16" in a terminal, it launches Gaussian16. So, would it be redundant or create a conflict if I additionally exported g16 as follows?

export g16root="/home/rjrich/zware/g16/g16"

Thanks.

-- RJR

**Comment by MatthijsHak** [comment]
Hi,

If your system is able to find the executable and launch Gaussian correctly then your environment variable is set properly. Changing this would lead to conflicts.
