### ISSUE TITLE
MetalDock Setup -- ORCA (Linux)

### ISSUE THREAD

**Issue by rjrich** [MatthijsHak/MetalDock#28]
In the MetalDock setup instructions for ORCA, it says to export the full path to the binary as follows:

export ASE_ORCA_COMMAND='/full/path/to/orca/orca PREFIX.inp > PREFIX.out'

However, the ORCA instructions indicate the following exports:

export PATH="/home/rjrich/zware/orca:$PATH"
export LD_LIBRARY_PATH="/home/rjrich/zware/orca:$LD_LIBRARY_PATH"

I have the above two exports in my ".bashrc" file.

For parallel execution, the ORCA instructions recommend calling orca with the full path:

$PATH/orca $jobname.inp

Is the same thing accomplished by adding the line you have suggested to my ".bashrc" file?

export ASE_ORCA_COMMAND='/full/path/to/orca/orca PREFIX.inp > PREFIX.out'

I currently have it set up this way in ".bashrc":

# ORCA 5.04
export PATH="/home/rjrich/zware/orca:$PATH"
export LD_LIBRARY_PATH="/home/rjrich/zware/orca:$LD_LIBRARY_PATH"
export ASE_ORCA_COMMAND='/home/rjrich/zware/orca/orca PREFIX.inp > PREFIX.out'

However, when I try to run MetalDock with more than 1 cpu process, ORCA crashes. On the other hand, it runs with ncpu = 1. So, it seems that something is wrong with my parallel setup for ORCA.

Thanks.

-- RJR

**Comment by MatthijsHak** [comment]
Fixed this issue via email correspondence.
