### ISSUE TITLE
MetalDock -- Documentation Apparent Errors

### ISSUE THREAD

**Issue by rjrich** [MatthijsHak/MetalDock#29]
In the MetalDock documentation, there seem to be a few errors or typos:

For the parameter file:

1. Under "memory", the default input says "ncpu = 3000". I assume this should be "mem = 3000" (?).

2. "box_size" is listed twice.

3.  "scale_factor", the default input says "box_size =" Is this correct?

4.  "random_pos", the default input says "box_size = True" (?)

5.  For "e_NA", "e_OA", "e_SA", and "e_HD", the default input for each is listed as "box_size = 5.0" (?).

Additional questions:

1. I setup a subdirectory under Desktop for the MetalDock input files. If the parameter_file, pdb_file, and xyz_file are also in this subdirectory, is it necessary to specify the full path to these files?

2. Could you add suggestions in the Documentation on how to determine the charge and spin of the ligand as well as how to determine if there is a vacant site in the first coordination sphere? In addition, it would be helpful to include some guidance on the optimal selection of basis sets and functionals.

Thank you!

-- RJR

**Comment by MatthijsHak** [comment]
Hi,

Thank you for notifying these apparent errors in the documentation. I have corrected them accordingly. For your two questions:

1. Relative paths also work with MetalDock, so if it is in the same directory from where you execute MetalDock no path specification is necessary.
2. I have added some information on how to determine charge and spin, as well as some references to papers that describe the process of choosing a basis set and functional.
