### ISSUE TITLE
Error When Adding and Optimizing H-atoms

### ISSUE THREAD

**Issue by rjrich** [MatthijsHak/MetalDock#32]
When docking a ferrocene complex to a protein, getting error at the stage of adding and optimizing hydrogen atoms to the metal complex poses:

AttributeError: 'NoneType' object has no attribute 'SetImplicitHCount'

Input files attached.

[input.zip](https://github.com/user-attachments/files/15740502/input.zip)

**Comment by MatthijsHak** [comment]
Hi,

I believe I have fixed your problem. Could you retry the latest repository and let me know if everything works accordingly?
