### ISSUE TITLE
Error: No Orca Configuration

### ISSUE THREAD

**Issue by Stefano-DFT** [MatthijsHak/MetalDock#34]
Dear All,
after completing the installation process, I encountered the following error:
$ metaldock -i input.ini 
Traceback (most recent call last):
  File "/home/stefano/MetalDock/metaldock", line 6, in <module>
    main()
  File "/home/stefano/MetalDock/src/metal_dock/main.py", line 18, in main
    docking(par)
  File "/home/stefano/MetalDock/src/metal_dock/docking.py", line 80, in docking
    qm_dir, energy = orca.orca_engine(xyz_file, par, output_dir)
  File "/home/stefano/MetalDock/src/metal_dock/orca_engine.py", line 22, in orca_engine
    orca_geom_opt(xyz_file, var)
  File "/home/stefano/MetalDock/src/metal_dock/orca_engine.py", line 109, in orca_geom_opt
    mol.calc = ORCA(label='geom',
  File "/home/stefano/anaconda3/envs/MetalDock/lib/python3.8/site-packages/ase/calculators/orca.py", line 95, in __init__
    super().__init__(template=OrcaTemplate(),
  File "/home/stefano/anaconda3/envs/MetalDock/lib/python3.8/site-packages/ase/calculators/genericfileio.py", line 274, in __init__
    raise BadConfiguration(f'No configuration of {template.name}')
ase.calculators.calculator.BadConfiguration: No configuration of orca

It seems that there is a communication issue between ASE and ORCA but I haven't been able to find a solution. Any assistance in resolving this issue would be greatly appreciated. Thank you!

**Comment by MatthijsHak** [comment]
Hi,

Did you export the following variable correctly?

export ASE_ORCA_COMMAND='/sw/arch/RHEL8/EB_production/2022/software/ORCA/5.0.4-foss-2022a/bin/orca PREFIX.inp > PREFIX.out'

This line is required for communication between ASE and ORCA. The path is system dependent, so you need to change this for yours.

**Comment by MatthijsHak** [comment]
Hi, 

From the screenshot that you have sent the path is not correctly set by $ASE_ORCA_COMMAND. Nothing is printed when you echo $ASE_ORCA_COMMAND. You should see something like this:


mhakkennes@int5:~$ export ASE_ORCA_COMMAND=/root/path/to/metaldock
mhakkennes@int5:~$ echo $ASE_ORCA_COMMAND
/root/path/to/metaldock
mhakkennes@int5:~$ 

If you copy your path here and run this command in the terminal it should work. You can also set it as environment variable in your shell script.

Let me know if it worked.

Regards,

Matthijs

**Comment by Stefano-DFT** [comment]
Dear Matthij, 
Thank you very much for your response and sorry for the inconvenience. In the previous post, I forgot to declare it; however, I am still encountering the following error. Thanks again!

![screenshot2](https://github.com/MatthijsHak/MetalDock/assets/172082027/ef63c304-c2c3-40aa-94a1-c86b33b05881)

**Comment by MatthijsHak** [comment]
Could you try to install ase== 3.22.1? You can do that by typing pip install  ase== 3.22.1

**Comment by Layr-Allysson** [comment]
I am experiencing the same issue. I followed all the instructions carefully, including setting up the PATH, configuring the ASE_ORCA_COMMAND, and ensuring the correct version of ase is installed. However, I am still encountering the "No configuration of orca" error. I have verified the PATH, checked file permissions, and ensured all necessary files are present. Despite these efforts, the problem persists.

Could you please provide further guidance on how to resolve this issue? Any help would be greatly appreciated.

Thank you.

**Comment by Stefano-DFT** [comment]
Dear Matthijs, 
I have installed the older version ase 3.22.1 as you suggested and now is correctly working, thanks a lot for your time !

**Comment by MatthijsHak** [comment]
Thanks for letting me know, probably there is something wrong with the latest ase version. I have adjusted the docs accordingly. @Layr-Allysson can you verify that this also works for you?

**Comment by Layr-Allysson** [comment]
Hi @MatthijsHak ,
I have redone all the steps, and now it is working correctly! Thank you very much for your help and guidance.
