### ISSUE TITLE
SCF convergence issue

### ISSUE THREAD

**Issue by chuochen** [MatthijsHak/MetalDock#37]
Hello,

I'm trying to use MetalDock with ORCA as the QM engine. However, I ran into "SINGLE POINT NOT CONVERGED - DELETE geom.out" soon after executing the .ini file (also happened with the example_run file 1jzi_D_REP). The same .xyz file converged when running the SVP subprocess independently in ORCA. Is there a way to extend the SCF iterations or overwrite the convergence criteria using the .ini file?

Thank you,

CC

**Comment by MatthijsHak** [comment]
Hi,

Are you sure that it is due to convergence or SCF iterations issues? Can you share with me all the files in the  the output/QM directory. 

I do think that adding the option to specify SCF iterations / convergence criteria is a good idea, so I will try to implement that asap.

Regards,

Matthijs

**Comment by chuochen** [comment]
Hi Matthijs,

It generated four files (single_point.ase, .inp, and .out in addition to the .xyz input file--cannot attach here so sent by email separately) in output/QM/single_point. The single_point.out file is empty (0 bytes). There's nothing under geom_opt (geom_opt=False was used). The only message I got is from the terminal: "SINGLE POINT NOT CONVERGED - DELETE geom.out".

Many thanks for your help!

CC

**Comment by MatthijsHak** [comment]
If the single_point.out file is empty, it means that the connection between ASE and ORCA is not correctly set. Did you run the following export command in your terminal before running MetalDock:

export ASE_ORCA_COMMAND='/full/path/to/orca/orca PREFIX.inp > PREFIX.out'

**Comment by chuochen** [comment]
Yes, otherwise the program would return with orca command not found and a series of orca calculator failure.

**Comment by chuochen** [comment]
Here is the output folder. I use the example input.ini in the latest try. Thanks!
[output.zip](https://github.com/user-attachments/files/16378393/output.zip)

**Comment by MatthijsHak** [comment]
Okay, so I were able to reproduce the error and the exact status of your files. As I thought, the connection between ase and orca is not correctly set. If you run the script a first time you indeed get an ase orca error:

ase.calculators.calculator.CalculationFailed: Calculator "orca" failed with command "orca single_point.inp > single_point.out" failed

However, the output directory and files have been created, as well as the empty single_point.out file. If you then run it a second time, MetalDock will examine the single_point.out file and reads not a successful run, resulting in the printed message: 

ONLY ONE BOX SIZE GIVEN, SETTING BOX SIZE TO CUBIC
SINGLE POINT NOT CONVERGED - VERIFY THE PROBLEM IN single_point.out AND DELETE FILE BEFORE RUNNING AGAIN

You should therefore delete `rm -r output` directory and make sure that the environment variable is correctly set and rerun again. You should either get an error that ase is not properly set, or it should run.
