### ISSUE TITLE
ASE/ORCA connection issue

### ISSUE THREAD

**Issue by LLayug** [MatthijsHak/MetalDock#38]
Hello! I believe I may have an issue with ase/orca running. I have tried both

export ASE_ORCA_COMMAND='/full/path/to/orca/orca PREFIX.inp > PREFIX.out' — as mentioned on the readthedocs

and 

export ASE_ORCA_COMMAND=/root/path/to/metaldock — as mentioned in some other issue posts

However, I still get this issue when running the test files https://github.com/MatthijsHak/MetalDock/tree/main/examples/example_runs/vacancy_coordination_sphere/ORCA:

ase.calculators.calculator.CalculationFailed: Calculator "orca" failed with command "/Users/macbookair/Applications/orca_5-0-4  single_point.inp > single_point.out" failed in /Users/macbookair/Downloads/Test/output/QM/single_point with error code 126

I also get the same issues running other files that have worked on another labmate's computer that runs metaldock properly. I have installed ase 3.22.1, as suggested, but still no luck.

Thank you!

**Comment by MatthijsHak** [comment]
It looks from your path that you do not explicitly set the path to orca binary. Within the bin directory of the orca directory, there should be an orca executbale. The path should be set to this file.

**Comment by LLayug** [comment]
Hello! Even as I set the full path to orca in the ASE_ORCA_COMMAND as the path to the orca executable itself, it still gives me a similar error:

ase.calculators.calculator.CalculationFailed: Calculator "orca" failed with command "orca single_point.inp > single_point.out" failed in /Users/macbookair/Desktop/Mdock-Test-Files/Test-GHub/output/QM/single_point with error code 125

**Comment by MatthijsHak** [comment]
I am sorry, but it still looks to me that this is the problem. The path that you specify here is not an executable, but looks like a folder:

/Users/macbookair/Applications/orca_5-0-4 single_point.inp > single_point.out

While the error command here only states orca:

orca single_point.inp > single_point.out

If you type in orca in you command line and it runs orca, then the path executable is correclty set. If it does not run ORCA, you need to specify the correct path to the orca executable, such that when typing in that path, ORCA runs. If you are able to run ORCA from the command line, please share with me the files from the single point output directory.
