### ISSUE TITLE
MetalDock Setup -- Package Download Issue

### ISSUE THREAD

**Issue by alkynezipper** [MatthijsHak/MetalDock#39]
When trying to install required packages for MetalDock, I get the error:

xtb-6.5.1| Program python3 found: YES (/opt/anaconda3/envs/MetalDock/bin/python3.8)
      xtb-6.5.1| Configuring xtb_version.fh using configuration
      xtb-6.5.1| ../subprojects/xtb-6.5.1/meson/meson.build:22: WARNING: FC and CC are not from the same vendor
      
      ../subprojects/xtb-6.5.1/meson/meson.build:115:23: ERROR: C shared or static library 'mkl_gf_lp64' not found
      
      A full log can be found at /private/var/folders/sx/h7hs9s3n34585fqlkghj8zpr0000gn/T/pip-install-zvvzvqml/xtb_5a574d05568c49199a5b1f69955a2c0e/.mesonpy-ujedlo4m/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

I also cannot find the full log file in /private/var/folders/...

Thanks.

**Comment by MatthijsHak** [comment]
Hi,

I am sorry, but I cannot help you with installation issues of other packages. I would recommend you to post this problem on the xtb github page.
