### ISSUE TITLE
Single Point Issue

### ISSUE THREAD

**Issue by Johnson7L** [MatthijsHak/MetalDock#8]
Dear MatthijsHak,

did you ever try to run with the input parameter "geom_opt=False", there might be some issues? In "MetalDock/src/metal_dock/orca_engine.py", the  "mol.write('output.xyz')" in the section "def orca_single_point(xyz_file, var)" is missing.

Additionally, did you encounter the situation that the metal-ligand structrue is not reasonable after docking? As following shown, the cymene struture after docking is indeed not reasonable.

![after optimization](https://github.com/MatthijsHak/MetalDock/assets/137474155/19c9f813-1f8a-4deb-b99a-a979fd962566)
![after docking](https://github.com/MatthijsHak/MetalDock/assets/137474155/6e8ef2ad-1449-4d54-b7d0-9d2499d0a039)

Regards,
Z.LIN.

**Comment by MatthijsHak** [comment]
Dear Z. Lin,

I really appreciate the help with finding all bugs. I have changed the ORCA single point file such that it now works properly. 

Regarding the docking structures, I have not encountered problems with cymene. Could you perhaps send me the directory, especially the pdbqt files. Sometimes pymol does not generate the structures properly. 

Once again, thank you for the help.

Regards,

Matthijs

**Comment by Johnson7L** [comment]
Dear Matthijs,

If I would like to get RMSD, for instance, I need to abstract the xyz file of the ligand from the 1JZE.pdb in your paper. Should the 1JZE.pdb file be edited? Or can the 1jze.pdb downloaded from RCSB directly be used for the metaldock simulation?

Regards,
Zexiong
