### ISSUE TITLE
Monte Carlo Running Issue

### ISSUE THREAD

**Issue by Johnson7L** [MatthijsHak/MetalDock#9]
Dear Matthijs,

I would like to run Monte Carlo on metaldock. However, I am not sure which input files should I create. Could you give me an example?

Regards,
Z.LIN.

**Comment by MatthijsHak** [comment]
Dear Z.Lin, 

I have added an example directory to this post. Be sure that in the data_set directory every subdirectory is named protein_x where x is a number. Also run each subdirectory before starting the Monte Carlo run, such that all necessary files are generated. 

[example_MC.zip](https://github.com/MatthijsHak/MetalDock/files/13209216/example_MC.zip)

Regards,

Matthijs
